
version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_wavetrend
    environment:
      MYSQL_ROOT_PASSWORD: flower
      MYSQL_DATABASE: wavetrend
      MYSQL_USER: l-ted
      MYSQL_PASSWORD: p-ted
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: flower

  ltcusdt_15:
    build: .
    image: wave-monitor-ltcusdt
    container_name: wave-monitor-ltcusdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=LTCUSDT
      - INTERVAL=15
      - START_DELAY=1
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-LTCUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  manausdt_15:
    build: .
    image: wave-monitor-manausdt
    container_name: wave-monitor-manausdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=MANAUSDT
      - INTERVAL=15
      - START_DELAY=4
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-MANAUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  solusdt_15:
    build: .
    image: wave-monitor-solusdt
    container_name: wave-monitor-solusdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=SOLUSDT
      - INTERVAL=15
      - START_DELAY=0
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-SOLUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  xrpusdt_15:
    build: .
    image: wave-monitor-xrpusdt
    container_name: wave-monitor-xrpusdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=XRPUSDT
      - INTERVAL=15
      - START_DELAY=2
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-XRPUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  adausdt_15:
    build: .
    image: wave-monitor-adausdt
    container_name: wave-monitor-adausdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=ADAUSDT
      - INTERVAL=15
      - START_DELAY=1
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-ADAUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  eosusdt_15:
    build: .
    image: wave-monitor-eosusdt
    container_name: wave-monitor-eosusdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=EOSUSDT
      - INTERVAL=15
      - START_DELAY=3
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-EOSUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  btcusdt_15:
    build: .
    image: wave-monitor-btcusdt
    container_name: wave-monitor-btcusdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=BTCUSDT
      - INTERVAL=15
      - START_DELAY=3
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-BTCUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  ethusdt_15:
    build: .
    image: wave-monitor-ethusdt
    container_name: wave-monitor-ethusdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=ETHUSDT
      - INTERVAL=15
      - START_DELAY=3
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-ETHUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  arbusdt_15:
    build: .
    image: wave-monitor-arbusdt
    container_name: wave-monitor-arbusdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=ARBUSDT
      - INTERVAL=15
      - START_DELAY=3
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-ARBUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  dotusdt_15:
    build: .
    image: wave-monitor-dotusdt
    container_name: wave-monitor-dotusdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=DOTUSDT
      - INTERVAL=15
      - START_DELAY=4
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-DOTUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  1000pepeusdt_15:
    build: .
    image: wave-monitor-1000pepeusdt
    container_name: wave-monitor-1000pepeusdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=1000PEPEUSDT
      - INTERVAL=15
      - START_DELAY=3
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-1000PEPEUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  crousdt_15:
    build: .
    image: wave-monitor-crousdt
    container_name: wave-monitor-crousdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=CROUSDT
      - INTERVAL=15
      - START_DELAY=2
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-CROUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  bnbusdt_15:
    build: .
    image: wave-monitor-bnbusdt
    container_name: wave-monitor-bnbusdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=BNBUSDT
      - INTERVAL=15
      - START_DELAY=2
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-BNBUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  dogeusdt_15:
    build: .
    image: wave-monitor-dogeusdt
    container_name: wave-monitor-dogeusdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=DOGEUSDT
      - INTERVAL=15
      - START_DELAY=5
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-DOGEUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  suiusdt_15:
    build: .
    image: wave-monitor-suiusdt
    container_name: wave-monitor-suiusdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=SUIUSDT
      - INTERVAL=15
      - START_DELAY=2
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-SUIUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  1000bonkusdt_15:
    build: .
    image: wave-monitor-1000bonkusdt
    container_name: wave-monitor-1000bonkusdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=1000BONKUSDT
      - INTERVAL=15
      - START_DELAY=3
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-1000BONKUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  icpusdt_15:
    build: .
    image: wave-monitor-icpusdt
    container_name: wave-monitor-icpusdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=ICPUSDT
      - INTERVAL=15
      - START_DELAY=3
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-ICPUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  mntusdt_15:
    build: .
    image: wave-monitor-mntusdt
    container_name: wave-monitor-mntusdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=MNTUSDT
      - INTERVAL=15
      - START_DELAY=1
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-MNTUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

  tonusdt_15:
    build: .
    image: wave-monitor-tonusdt
    container_name: wave-monitor-tonusdt-15
    environment:
      - BYBIT_API_KEY_DEMO=${BYBIT_API_KEY_DEMO}
      - BYBIT_SECRET_KEY_DEMO=${BYBIT_SECRET_KEY_DEMO}
      - SYMBOL=TONUSDT
      - INTERVAL=15
      - START_DELAY=2
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=l-ted
      - DB_PASSWORD=p-ted
      - DB_NAME=wavetrend
    volumes:
      - ./config/config-TONUSDT-15.json:/app/config.json
    restart: unless-stopped
    network_mode: host

volumes:
  mysql_data:
